services:
  web:
    &WEB
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=popcornhub.settings
      - DB_NAME=popcornhub
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5433
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SKIP_MIGRATIONS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    <<: *WEB
    ports: []
    entrypoint: []
    command: >
      sh -c "
        cd popcornhub &&
        echo 'Waiting for PostgreSQL...' &&
        while ! nc -z $$DB_HOST $$DB_PORT; do sleep 0.1; done &&
        echo 'PostgreSQL started' &&
        echo 'Waiting for Redis...' &&
        while ! nc -z redis 6379; do sleep 0.1; done &&
        echo 'Redis started' &&
        celery -A popcornhub worker --beat --loglevel=info
      "
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started

  db:
    image: postgres:13
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=popcornhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    name: popcornhub_postgres_data