# Generated by Django 4.2.16 on 2025-01-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovie',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
