# Generated by Django 4.2.16 on 2025-01-20 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_historicalmovie_total_ratings_movie_total_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['name'], 'verbose_name': 'Cinema', 'verbose_name_plural': 'Cinemas'},
        ),
        migrations.AlterModelOptions(
            name='historicalactor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Actor', 'verbose_name_plural': 'historical Actors'},
        ),
        migrations.AlterModelOptions(
            name='historicalcinema',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cinema', 'verbose_name_plural': 'historical Cinemas'},
        ),
        migrations.AlterModelOptions(
            name='historicalmovie',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Movie', 'verbose_name_plural': 'historical Movies'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='subtitle_file',
            field=models.TextField(blank=True, help_text='Upload SRT or VTT subtitle file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='trailer_video',
            field=models.TextField(blank=True, help_text='Upload movie trailer (MP4, MOV)', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitle_file',
            field=models.FileField(blank=True, help_text='Upload SRT or VTT subtitle file', null=True, upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(blank=True, help_text='Upload movie trailer (MP4, MOV)', null=True, upload_to='trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movie_actors', to='showcase.movie'),
        ),
        migrations.AlterField(
            model_name='historicalmovie',
            name='status',
            field=models.CharField(choices=[('soon', 'Upcoming'), ('now', 'Theaters'), ('end', 'Ended')], default='soon', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalmovierating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Rating cannot be less than 1'), django.core.validators.MaxValueValidator(10, 'Rating cannot be greater than 10')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('soon', 'Upcoming'), ('now', 'Theaters'), ('end', 'Ended')], default='soon', max_length=10),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Rating cannot be less than 1'), django.core.validators.MaxValueValidator(10, 'Rating cannot be greater than 10')]),
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('is_main_role', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.movie')),
            ],
            options={
                'unique_together': {('movie', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='acted_in_movies', through='showcase.MovieActor', to='showcase.actor'),
        ),
    ]
