# Generated by Django 4.2.16 on 2025-01-22 07:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0003_alter_actor_options_alter_cinema_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmovierating',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmovierating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='historicalmovierating',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={'verbose_name': 'Movie Rating', 'verbose_name_plural': 'Movie Ratings'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_favorites', to='showcase.movie'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='showcase.movie'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='HistoricalFavorite',
        ),
        migrations.DeleteModel(
            name='HistoricalMovieRating',
        ),
    ]
