# Generated by Django 4.2.16 on 2025-01-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_uservisit_historicaluservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovie',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
