# Generated by Django 4.2.16 on 2025-01-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_historicalmovie_average_rating_movie_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservisit',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalUserVisit',
        ),
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
