# Generated by Django 4.2.16 on 2025-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_remove_uservisit_user_delete_historicaluservisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='showcase.movie'),
        ),
    ]
